global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'app-demo'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8080']
        labels:
          application: "app-demo" #será exibido no Application do Grafana

#  - job_name: 'spring-actuator'
#    metrics_path: '/actuator/metrics'
#    scrape_interval: 5s
#    static_configs:
#      - targets: ['host.docker.internal:8080'] #Ver IPV4 com comando ipconfif no Windows ou ifconfig no Linux
